### ISSUE TITLE
The last widget item jumps if it is selected

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#1113]
This style:

```css
/* content-styles.css */
.ck.ck-content > :last-child {
	margin-bottom: 0;
}
```
![selection_082](https://user-images.githubusercontent.com/247363/41916690-e35ebc40-7958-11e8-8e6e-2c0844a02f05.png)

Does not work when table widget is selected:
![selection_083](https://user-images.githubusercontent.com/247363/41916688-e0eea65a-7958-11e8-8e73-50bb6566b722.png)

ps.: Moved from cksource/umberto#554
