### ISSUE TITLE
Feature Request: Automatic numbering of headings

### ISSUE THREAD

**Issue by yvonnesun1** [ckeditor/ckeditor5#11204]
## 📝 options for automatic numbering headings like Word. 

_What is the expected behavior of the proposed feature?_
You can number headings so that top-level headings (Heading 1) are numbered 1, 2, 3, for example, and second-level headings (Heading 2) are numbered 1.1, 1.2, 1.3. And when removing one of the headings the rest of the heading numbers are automatically adjusted. 
---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by zhangyue000** [comment]
Any progress？

**Comment by CKEditorBot** [comment]
There has been no activity on this issue for the past year. We've marked it as stale and will close it in 30 days. We understand it may be relevant, so if you're interested in the solution, leave a comment or reaction under this issue.

**Comment by mdekermadec** [comment]
I found a CSS workaround to achieve this :

```css
.ck-content { counter-reset: h1 h2 h3 h4 h5 h6; }

.ck-content h1 {
 counter-increment: h1;
 counter-set: h2 0 h3 0 h4 0 h5 0 h6 0;
}
.ck-content h2 {
 counter-increment: h2;
 counter-set: h3 0 h4 0 h5 0 h6 0;
}
.ck-content h3 {
 counter-increment: h3;
 counter-set: h4 0 h5 0 h6 0;
}
.ck-content h4 {
 counter-increment: h4;
 counter-set: h5 0 h6 0;
}
.ck-content h5 {
 counter-increment: h5;
 counter-set: h6 0;
}
.ck-content h6 {
 counter-increment: h6;
}

.ck-content h1::before { content: counter(h1) '.\0000a0\0000a0'; }
.ck-content h2::before { content: counter(h1) '.' counter(h2) '.\0000a0\0000a0'; }
.ck-content h3::before { content: counter(h1) '.' counter(h2) '.' counter(h3) '.\0000a0\0000a0'; }
.ck-content h4::before { content: counter(h1) '.' counter(h2) '.' counter(h3) '.' counter(h3) '.' counter(h3) '.\0000a0\0000a0'; }
.ck-content h5::before { content: counter(h1) '.' counter(h2) '.' counter(h3) '.' counter(h3) '.' counter(h3) '.' counter(h3) '.' counter(h3) '.\0000a0\0000a0'; }
.ck-content h6::before { content: counter(h1) '.' counter(h2) '.' counter(h3) '.' counter(h3) '.' counter(h3) '.' counter(h3) '.' counter(h3) '.' counter(h3) '.\0000a0\0000a0'; }
```
