### ISSUE TITLE
ck-balloon-panel not visible using Bootstrap 4 modal (z-index).

### ISSUE THREAD

**Issue by ghost** [ckeditor/ckeditor5#1142]
## Is this a bug report or feature request? (choose one)

🐞 Bug report

## 💻 Version of CKEditor

5 latest

## 📋 Steps to reproduce

`.ck-balloon-panel` not visible using Bootstrap 4 modal (z-index lower).

Is there a way to customize z-index?

**Comment by dkonopka** [comment]
Hello @johnunclesam, [CKEditor 5 is using `1000` value as default z-index for balloons](https://github.com/ckeditor/ckeditor5-ui/blob/master/theme/globals/_zindex.css), but you can eaisly change it via CSS Variables.

As I can see [bootstrap 4 is using 1070 as maximum z-value](https://getbootstrap.com/docs/4.0/layout/overview/#z-index), so you need to add this code in your stylesheet or directly in HTML:

```css
:root {
   --ck-z-default: 100
}
```

You can find more details about theme customization in our [documentation](https://docs.ckeditor.com/ckeditor5/latest/framework/guides/ui/theme-customization.html).

**Comment by Reinmar** [comment]
> As I can see bootstrap 4 is using 1070 as maximum z-value, so you need to add this code in your stylesheet or directly in the HTML file:

So, shouldn't you use `1071+`? Like:

```css
:root {
   --ck-z-default: 2000;
}
```

**Comment by dkonopka** [comment]
> So, shouldn't you use 1071+ to display CKE5's balloons over Bootstrap 4 modals? Like:

[We have introduced relative z-indexes values recently](https://github.com/ckeditor/ckeditor5-ui/issues/412), so you need to change only one default property in our CSS Variables set. 

[Balloons in CKE5 are using `--ck-z-modal` variable](https://github.com/ckeditor/ckeditor5-ui/blob/master/theme/components/panel/balloonpanel.css#L15), so changing `--ck-z-default` to 100 will be enough.

**Comment by dkonopka** [comment]
> Won't that display CKEditor 5 below the Bootstrap's modal? 

No, CKE5 content will be still visible, [take a look at live demo with bootstrap 4 modal](https://codepen.io/k0n0pka/pen/yqBXOz).

**Comment by Reinmar** [comment]
Sorry. I didn't know that we defined `--ck-z-modal` as this: [`--ck-z-modal: calc( var(--ck-z-default) + 999 );`](https://github.com/ckeditor/ckeditor5-ui/blob/master/theme/globals/_zindex.css#L8) which results in `z-index: 1099` so, more than `1071`.

**Comment by Reinmar** [comment]
I'm closing this ticket as resolved as this is something to be configured on integration's side. The solution is to define:

```css
:root {
   --ck-z-default: 100
}
```

as @dkonopka pointed out above.

**Comment by oskarwrobel** [comment]
When CKE5 is displayed inside the modal then its default z-index should be the modal z-index + 1. CKE5 z-index stack should start above the modal.

**Comment by johnunclesam** [comment]
I think @oskarwrobel is right. I don't have to write my own code. Am I right, @Reinmar?

**Comment by dkonopka** [comment]
My solution wasn't wrong, but as @oskarwrobel said:
```css
:root {
  /* Because maximum bootstrap z-index is 1070. */
   --ck-z-default: 1071
}
```
is more "bulletproof".

**Comment by oskarwrobel** [comment]
When CKE5 is in the modal and z-index of this modal is `500`, then CKE5 default `z-index` should be set as `501` and it have to be done on the integration side.

**Comment by Reinmar** [comment]
What if some other framework sets their `z-index` to `9999`?

What about parts of other websites' UIs which should be displayed over the editor? What if a Bootstrap modal should never be covered by CKEditor 5's panel. Now we're talking about displaying CKEditor 5 in a Bootstrap modal, but what if Bootstrap modal is used as a part of CKEditor 5's UI and will suddenly hide beneath it?

So, sure, we can bump the default. Bootstrap is a popular framework and in most cases, it will be CKE5 used inside Bootstrap's modal, so perhaps it makes sense. But it's not the last time we'll be asked about this. You can also break existing integrations when changing the default (e.g. our docs). So just take this into consideration when making a decision.

**Comment by dkonopka** [comment]
☝️ Agree, if we set the biggest possible value it will start `z-index war` between CKE5 and other frameworks. 

To sum up, I would choose the minimum working solution for now where `ck-z-default` is `100`.

**Comment by oskarwrobel** [comment]
Guys, I would not change anything here. We introduced relative z-index to make the integration easy. It's the developer responsibility to set a proper default `z-index` for CKE5. When the editor is placed on the modal then the default z-index should be increased to be the same as the modal one. Only the person who integrates the editor knows the proper value.

**Comment by oskarwrobel** [comment]
> To sum up, I would choose the minimum working solution for bootstrap 4 where ck-z-default is 100.

What if we introduce something in our UI with z-index 200? I will land under the modal.

> What about parts of other websites' UIs which should be displayed over the editor? What if a Bootstrap modal should never be covered by CKEditor 5's panel. Now we're talking about displaying CKEditor 5 in a Bootstrap modal, but what if Bootstrap modal is used as a part of CKEditor 5's UI and will suddenly hide beneath it?

We have a [set of variables](https://github.com/ckeditor/ckeditor5-ui/blob/963b926bc9068affc0b534822f4963f06b224b63/theme/globals/_zindex.css#L7-L8) everything can be controlled separately to fit the integration.

**Comment by Reinmar** [comment]
I wrote such a section about Bootstrap integration. Do we need to do anything else?

---

## Compatibility with Bootstrap

In order to display CKEditor 5 inside [Bootstrap](https://getbootstrap.com/) modals you need to configure two things:

* The `z-index` of CKEditor 5's floating balloons so they are displayed above the Bootstrap's overlay.
* Configure Bootstrap to not steal focus from CKEditor 5 fields.

The above can be ensured by adding this CSS:

```css
/*
	We need to add this CSS custom property to the body instead of :root,
	because of CSS specificity.
*/
body {
	--ck-z-default: 100;
	--ck-z-modal: calc( var(--ck-z-default) + 999 );
}

/*
	Override Bootstrap's CSS.
	Note: this won't be necessary once the following issue is fixed and released:
	https://github.com/ckeditor/ckeditor5-theme-lark/issues/189
*/
.ck.ck-button {
	-webkit-appearance: none;
}
```

And passing the `focus: false` option to Boostrap's `modal()` function:

```js
$( '#modal-container' ).modal( {
	focus: false
} );
```

Check out the demo on https://codepen.io/k0n0pka/pen/yqBXOz.

**Comment by Reinmar** [comment]
I see that @oskarwrobel agrees (https://github.com/ckeditor/ckeditor5/issues/1142#issuecomment-404084316), so I'm closing this.

**Comment by oskarwrobel** [comment]
Now I see that `--ck-z-default` does not make sense. I thought css variables works a bit different. I assumed that it's enough to define:
```css
:root {
  --ck-z-default: 1;
  --ck-z-modal: calc( var(--ck-z-default) + 999 );
}
```
and then we will be able to change everything only by changing `--ck-z-default`
```css
body.bootstrap-modal {
  --ck-z-default: 1051; /* Bootstrap modal + 1 */
}
```
and `--ck-z-modal` used inside `body.bootstrap-modal` will be calculated as `1051 + 999`.

But we need to override all:
```css
body.bootstrap-modal {
  --ck-z-default: 1051; /* Bootstrap modal + 1 */

  /* We need this line otherwise value of --ck-z-modal
  won't change and will be still calculated as 1 + 999 */
  --ck-z-modal: calc( var(--ck-z-default) + 999 ); 
}
```

**Comment by edgarsn** [comment]
> I wrote such a section about Bootstrap integration. Do we need to do anything else?
> 
> ## Compatibility with Bootstrap
> In order to display CKEditor 5 inside [Bootstrap](https://getbootstrap.com/) modals you need to configure two things:
> 
> * The `z-index` of CKEditor 5's floating balloons so they are displayed above the Bootstrap's overlay.
> * Configure Bootstrap to not steal focus from CKEditor 5 fields.
> 
> The above can be ensured by adding this CSS:
> 
> ```css
> /*
> 	We need to add this CSS custom property to the body instead of :root,
> 	because of CSS specificity.
> */
> body {
> 	--ck-z-default: 100;
> 	--ck-z-modal: calc( var(--ck-z-default) + 999 );
> }
> 
> /*
> 	Override Bootstrap's CSS.
> 	Note: this won't be necessary once the following issue is fixed and released:
> 	https://github.com/ckeditor/ckeditor5-theme-lark/issues/189
> */
> .ck.ck-button {
> 	-webkit-appearance: none;
> }
> ```
> 
> And passing the `focus: false` option to Boostrap's `modal()` function:
> 
> ```js
> $( '#modal-container' ).modal( {
> 	focus: false
> } );
> ```
> 
> Check out the demo on https://codepen.io/k0n0pka/pen/yqBXOz.

This worked for me. If you're using bootstrap-vue, then you should add `no-enforce-focus` to `<b-modal>`

**Comment by dipikaletsnurture** [comment]
I am using reactstrap modal with ckeditor5 and not able to edit the link input, can someone help here?

**Comment by lordaikins** [comment]
> I wrote such a section about Bootstrap integration. Do we need to do anything else?
> 
> ## Compatibility with Bootstrap
> In order to display CKEditor 5 inside [Bootstrap](https://getbootstrap.com/) modals you need to configure two things:
> 
> * The `z-index` of CKEditor 5's floating balloons so they are displayed above the Bootstrap's overlay.
> * Configure Bootstrap to not steal focus from CKEditor 5 fields.
> 
> The above can be ensured by adding this CSS:
> 
> ```css
> /*
> 	We need to add this CSS custom property to the body instead of :root,
> 	because of CSS specificity.
> */
> body {
> 	--ck-z-default: 100;
> 	--ck-z-modal: calc( var(--ck-z-default) + 999 );
> }
> 
> /*
> 	Override Bootstrap's CSS.
> 	Note: this won't be necessary once the following issue is fixed and released:
> 	https://github.com/ckeditor/ckeditor5-theme-lark/issues/189
> */
> .ck.ck-button {
> 	-webkit-appearance: none;
> }
> ```
> 
> And passing the `focus: false` option to Boostrap's `modal()` function:
> 
> ```js
> $( '#modal-container' ).modal( {
> 	focus: false
> } );
> ```
> 
> Check out the demo on https://codepen.io/k0n0pka/pen/yqBXOz.

This worked for me too, thanks for saving several hours spent on Google for a hack!

**Comment by panchicore** [comment]
Similar issue with Chakra-UI modals, fix with:

```css
:root {
  --ck-z-default: 2000;
}
```

they will appear, but if you are working with inline or balloon toolbars, the toolbar will disappear as soon as you want to click any toolbar item, the editor seems to lose the focus, so the solution is not to trap the focus on the modal:

```js
<Modal trapFocus={false}>
```
