### ISSUE TITLE
Wrong order of image styles at https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#11829]
CKEditor has:

```css
.ck-content .image {
  clear: both;
  display: table;
  margin: .9em auto;
  min-width: 50px;
  text-align: center
}

.ck-content .image-style-align-left {
  float: left;
  margin-right: var(--ck-image-style-spacing)
}

.ck-content .image-style-align-right {
  float: right;
  margin-left: var(--ck-image-style-spacing)
}
```

In the editor styles, the rule for `.ck-content .image` comes before the rules for `.ck-content .image-style-block-align-left` and `.ck-content .image-style-block-align-right`. So the `margin` setting from the latter styles takes precedence and all is well.

In the styles published at https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html, however, the rule for `.ck-content .image` comes after all imagestyle-related rules, so all images end up being centered even if `.image-style-block-align-left` or `.image-style-block-align-right` are applied to the image.
