### ISSUE TITLE
Content styles contains wrong entries regarding table column resize

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#11922]
## 📝 Provide detailed reproduction steps (if any)

**Building content styles using the documentation:**

1. Use `yarn run docs` for building the documentation.
2. Visit [the content styles page](https://ckeditor.com/docs/ckeditor5/34.1.0/installation/advanced/content-styles.html#the-full-list-of-content-styles)
3. Find the `.table-column-resizer` definition.

**Building content styles using a node script:**

1. Create the script file (e.g. `content-styles.js` in the root CKEditor 5 directory):

	  ```js
	  #!/usr/bin/env node
	  
	  /**
	   * @license Copyright (c) 2003-2022, CKSource Holding sp. z o.o. All rights reserved.
	   * For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
	   */
	  
	  /* eslint-env node */
	  
	  const buildContentStyles = require( './scripts/docs/build-content-styles' );
	  
	  buildContentStyles();
	  ```

2. Call `node content-styles.js`.
3. Open a file pointed out by the script (_Content styles have been extracted to ..._)
4. Find the `.table-column-resizer` definition.

### ✔️ Expected result

The content styles should not include `.table-column-resizer` definitions.

### ❌ Actual result

Content styles contain the following rules:

```css
/* ckeditor5-table/theme/tablecolumnresize.css */
.ck-content .table .table-column-resizer {
	position: absolute;
	top: -999999px;
	bottom: -999999px;
	right: var(--ck-table-column-resizer-position-offset);
	width: var(--ck-table-column-resizer-width);
	cursor: col-resize;
	user-select: none;
	z-index: var(--ck-z-default);
}
/* ckeditor5-table/theme/tablecolumnresize.css */
.ck-content .table[draggable] .table-column-resizer {
	display: none;
}
/* ckeditor5-table/theme/tablecolumnresize.css */
.ck-content .table .table-column-resizer:hover,
.ck-content .table .table-column-resizer__active {
	background-color: var(--ck-color-table-column-resizer-hover);
	opacity: 0.25;
}
/* ckeditor5-table/theme/tablecolumnresize.css */
.ck-content[dir=rtl] .table .table-column-resizer {
	left: var(--ck-table-column-resizer-position-offset);
	right: unset;
}
/* ckeditor5-table/theme/tablecolumnresize.css */
.ck-content.ck-read-only .table .table-column-resizer {
	display: none;
}
```

### ❓ Possible solution

Use `.ck.ck-editor__editable` instead of `.ck-content` in `tablecolumnresize.css`.

https://github.com/ckeditor/ckeditor5/blob/abe4468d87939920a0641dae8a44326eefea8f8c/packages/ckeditor5-table/theme/tablecolumnresize.css#L25

## 📃 Other details

* First affected CKEditor version: 34.1.0
* Installed CKEditor plugins: All from `ckeditor/ckeditor5` repository.
