### ISSUE TITLE
Clipboard CSS is not valid css

### ISSUE THREAD

**Issue by yukosgiti** [ckeditor/ckeditor5#12497]
## 📝 Provide detailed reproduction steps (if any)

[Clipboard css code has nested elements inside which is not valid css. ](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-clipboard/theme/clipboard.css)

### ✔️ Expected result

The css should not have nested selectors. I think somehow sass didn't compile it.

### ❌ Actual result

Denested css should be included. In fact the exact code:

```css
.ck.ck-editor__editable {
  /*
   * Vertical drop target (in text).
   */
  /*
   * Styles of the widget being dragged (its preview).
   */
}
.ck.ck-editor__editable .ck.ck-clipboard-drop-target-position {
  display: inline;
  position: relative;
  pointer-events: none;
}
.ck.ck-editor__editable .ck.ck-clipboard-drop-target-position span {
  position: absolute;
  width: 0;
}
.ck.ck-editor__editable .ck-widget:-webkit-drag > .ck-widget__selection-handle {
  display: none;
}
.ck.ck-editor__editable .ck-widget:-webkit-drag > .ck-widget__type-around {
  display: none;
}
```
(I used the online sass playground to transpile)
### ❓ Possible solution

Change the css code to above seems to work.

## 📃 Other details
my package json
```json
"dependencies": {
    "@ckeditor/ckeditor5-build-classic": "^35.1.0",
    "axios": "^0.27.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-hook-form": "^7.35.0"
  },
  "devDependencies": {
    "@types/ckeditor__ckeditor5-build-classic": "^29.0.1",
    "@types/ckeditor__ckeditor5-core": "^33.0.3",
    "@types/react-dom": "^18.0.6",
    "buffer": "^6.0.3",
    "parcel": "^2.7.0",
    "process": "^0.11.10",
    "typescript": "^4.8.3"
  }
```
---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.
