### ISSUE TITLE
how to hide border of the image when mouse over under readonly mode?

### ISSUE THREAD

**Issue by qiaqiaxian** [ckeditor/ckeditor5#1261]
## Is this a bug report or feature request? (choose one)

Other

## 💻 Version of CKEditor

CKEditor5

## 📋 Steps to reproduce

![qq 20180925151338](https://user-images.githubusercontent.com/21219815/45998843-ab218580-c069-11e8-8e0d-5642f7a94502.png)

the border arounded the image

## ✅ Expected result
No border

**Comment by jodator** [comment]
@qiaqiaxian AFAIK there is no direct solution but you can style the editing area by yourself.

When toogling read only mode add some class, ie `off` to the editing container and disable outline on `<figure>` in your CSS:

```css
.ck.off figure.image,
.ck.off figure.image:hover {
    outline: none;
}
```

@oleq / @Reinmar:  I've checked this and the editor does not set any CSS class on the editing area. Maybe we should add something in the read only mode so the developers could change CSS (i.e. gray out text)?

**Comment by dkonopka** [comment]
☝️ Good point @jodator, by default we should toggle class in the read-only mode. 

Anyway, there is a custom property for selected widget, so here is better solution:

```css
.ck-content.ck-content-readmode {
 --ck-widget-outline-thickness: 0;
}
```
