### ISSUE TITLE
“Powered by CKEditor” should not used fixed `fill` attributes

### ISSUE THREAD

**Issue by dtdesign** [ckeditor/ckeditor5#14819]
## 📝 Provide a description of the improvement

The text “CKEditor” adjacent to the logo uses the `fill` attribute in the SVG which is fine for light themes but makes it impossible to read it in a dark theme where it is placed on a dark background. It worked fine in v39.0.0 but the logo was later updated to introduce the `fill` attribute again.

The lack of any specific IDs makes it impossible to fix the contrast using CSS because it is not possible to target the “text” part of the SVG. Please drop the color values from the SVG itself entirely and move it into CSS classes (and possibly CSS variables?) so that it is possible to apply the proper contrast in dark themes.

The `fill` attribute was introduced here:
https://github.com/ckeditor/ckeditor5/compare/v39.0.0...v39.0.1#diff-f93151c1189731b5e9b81960fbbd1a079ebdecb1e6d41a5829a406d8bb2d0696

## 📃 Other details

* Browser: Not relevant.
* OS: Not relevant.
* CKEditor version: v39.0.1
* Installed CKEditor plugins: Not relevant.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Cc'ying @oleq.

**Comment by Reinmar** [comment]
We re-introduced the `fill` attribute as a fix to having it mistakenly removed by 39.0.0. It happened due to our SVG optimization script.

Let's wait for @oleq to comment on this.

**Comment by oleq** [comment]
I think reintroducing the fills to the logo does not change anything. With a few lines of CSS you can style it however you want to match your integration, including SVG paths in the logo

```css
.ck.ck-balloon-panel.ck-powered-by-balloon .ck.ck-powered-by {
    --ck-powered-by-text-color: fuchsia;    
}

.ck.ck-balloon-panel.ck-powered-by-balloon .ck.ck-powered-by svg * {
    fill: fuchsia;
}

.ck.ck-balloon-panel.ck-powered-by-balloon .ck.ck-powered-by {
    background: black;
}
```

<img width="294" alt="image" src="https://github.com/ckeditor/ckeditor5/assets/1099479/f534a8ac-cd10-4449-a8bc-30f489639dc5">

See more in https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/support/licensing/managing-ckeditor-logo.html#styling-customization.
