### ISSUE TITLE
How to change the background color of the ckeditor5 text area?

### ISSUE THREAD

**Issue by MohamedKarrab** [ckeditor/ckeditor5#15347]
How to change the background color of the ckeditor5 text area?

**Comment by Reinmar** [comment]
Add this CSS to your stylesheets:

```css
.ck-content { background: red !important }
```

Or use any other class available on this element:

![](https://github.com/ckeditor/ckeditor5/assets/156149/f4c9f776-c8cc-4ec6-8ede-493e102da8be)
