### ISSUE TITLE
Missing heading styles in "installation/advanced/content-styles.html"

### ISSUE THREAD

**Issue by surfinzap** [ckeditor/ckeditor5#15555]
### Origin URL

https://ckeditor.com/docs/ckeditor5/latest/installation/advanced/content-styles.html

### Project version

40.2.0

### Is there something missing in the guide? What is it?

I'd welcome heading styles in the list of content styles as an example to override. I'm assuming that something like this should probably work?
```css
.ck-content h1 {
  font-size: var(--custom-h1-font-size);
}

.ck-content hN {
...
}
```

### User agent

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
