### ISSUE TITLE
There is no easy way to apply styles to the document editable only

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#16552]
## 📝 Provide detailed reproduction steps (if any)

1. Create the following project:

	<details>
	<summary>index.html</summary>

	```html
	<!doctype html>
	<html lang="en">
		<head>
			<meta charset="utf-8">
			<title>CKEditor 5 Sample</title>
			<link rel="stylesheet" href="./style.css">
			<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ckeditor5@alpha/dist/browser/ckeditor5.css">
		</head>
		<body>
			<div class="main-container">
				<div
					class="editor-container editor-container_document-editor"
					id="editor-container"
				>
					<div class="editor-container__toolbar" id="editor-toolbar"></div>
					<div class="editor-container__editor-wrapper">
						<div class="editor-container__editor"><div id="editor"></div></div>
					</div>
				</div>
			</div>
			<script type="importmap">
			{
				"imports": {
					"ckeditor5": "https://cdn.jsdelivr.net/npm/ckeditor5@alpha/dist/browser/ckeditor5.js",
					"ckeditor5/": "https://cdn.jsdelivr.net/npm/ckeditor5@alpha/dist/"
				}
			}
			</script>
			<script type="module" src="./main.js"></script>
		</body>
	</html>
	```
	</details>
	<details>
	<summary>style.css</summary>

	```css
	@import url('https://fonts.googleapis.com/css2?family=Oswald&family=PT+Serif:ital,wght@0,400;0,700;1,400&display=swap');
	
	@import url('https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&display=swap');
	
	.main-container,
	.ck-content {
		font-family: 'Lato';
	}
	
	.main-container {
		width: fit-content;
		margin-left: auto;
		margin-right: auto;
	}
	
	.ck-content {
		word-break: break-word;
		line-height: 1.5;
		box-sizing: border-box;
		min-width: 210mm;
		max-width: 210mm;
		min-height: 297mm;
		height: fit-content;
		padding: 20mm 12mm;
		border: 1px hsl(0, 0%, 82.7%) solid;
		border-radius: 4px;
		background: hsl(0, 0%, 100%);
		box-shadow: 0 2px 3px hsla(0, 0%, 0%, 0.078);
		flex: 1 1 auto;
		margin-left: 72px;
		margin-right: 72px;
	}
	
	.editor-container__editor-wrapper {
		display: flex;
		width: fit-content;
	}
	
	.editor-container_document-editor {
		border: 1px solid var(--ck-color-base-border);
	}
	
	.editor-container_document-editor .editor-container__toolbar {
		display: flex;
		position: relative;
		box-shadow: 0 2px 3px hsla(0, 0%, 0%, 0.078);
	}
	
	.editor-container_document-editor .editor-container__toolbar > .ck.ck-toolbar {
		flex-grow: 1;
		width: 0;
		border-bottom-right-radius: 0;
		border-bottom-left-radius: 0;
		border-top: 0;
		border-left: 0;
		border-right: 0;
	}
	
	.editor-container_document-editor .editor-container__editor {
		margin-top: 28px;
		margin-bottom: 28px;
		height: 100%;
	}
	
	.ck-content h3.category {
		font-family: 'Oswald';
		font-size: 20px;
		font-weight: bold;
		color: #555;
		letter-spacing: 10px;
		margin: 0;
		padding: 0;
	}
	
	.ck-content h2.document-title {
		font-family: 'Oswald';
		font-size: 50px;
		font-weight: bold;
		margin: 0;
		padding: 0;
		border: 0;
	}
	
	.ck-content h3.document-subtitle {
		font-family: 'Oswald';
		font-size: 20px;
		color: #555;
		margin: 0 0 1em;
		font-weight: bold;
		padding: 0;
	}
	
	.ck-content p.info-box {
		--background-size: 30px;
		--background-color: #e91e63;
		padding: 1.2em 2em;
		border: 1px solid var(--background-color);
		background: linear-gradient(
			135deg,
		var(--background-color) 0%,
		var(--background-color) var(--background-size),
		transparent var(--background-size)
	),
		linear-gradient(
			135deg,
			transparent calc(100% - var(--background-size)),
		var(--background-color) calc(100% - var(--background-size)),
		var(--background-color)
	);
		border-radius: 10px;
		margin: 1.5em 2em;
		box-shadow: 5px 5px 0 #ffe6ef;
	}
	
	.ck-content blockquote.side-quote {
		font-family: 'Oswald';
		font-style: normal;
		float: right;
		width: 35%;
		position: relative;
		border: 0;
		overflow: visible;
		z-index: 1;
		margin-left: 1em;
	}
	
	.ck-content blockquote.side-quote::before {
		content: '“';
		position: absolute;
		top: -37px;
		left: -10px;
		display: block;
		font-size: 200px;
		color: #e7e7e7;
		z-index: -1;
		line-height: 1;
	}
	
	.ck-content blockquote.side-quote p {
		font-size: 2em;
		line-height: 1;
	}
	
	.ck-content blockquote.side-quote p:last-child:not(:first-child) {
		font-size: 1.3em;
		text-align: right;
		color: #555;
	}
	
	.ck-content span.marker {
		background: yellow;
	}
	
	.ck-content span.spoiler {
		background: #000;
		color: #000;
	}
	
	.ck-content span.spoiler:hover {
		background: #000;
		color: #fff;
	}
	
	.ck-content pre.fancy-code {
		border: 0;
		margin-left: 2em;
		margin-right: 2em;
		border-radius: 10px;
	}
	
	.ck-content pre.fancy-code::before {
		content: '';
		display: block;
		height: 13px;
		background: url(data:image/svg+xml;base64,PHN2ZyBmaWxsPSJub25lIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NCAxMyI+CiAgPGNpcmNsZSBjeD0iNi41IiBjeT0iNi41IiByPSI2LjUiIGZpbGw9IiNGMzZCNUMiLz4KICA8Y2lyY2xlIGN4PSIyNi41IiBjeT0iNi41IiByPSI2LjUiIGZpbGw9IiNGOUJFNEQiLz4KICA8Y2lyY2xlIGN4PSI0Ny41IiBjeT0iNi41IiByPSI2LjUiIGZpbGw9IiM1NkM0NTMiLz4KPC9zdmc+Cg==);
		margin-bottom: 8px;
		background-repeat: no-repeat;
	}
	
	.ck-content pre.fancy-code-dark {
		background: #272822;
		color: #fff;
		box-shadow: 5px 5px 0 #0000001f;
	}
	
	.ck-content pre.fancy-code-bright {
		background: #dddfe0;
		color: #000;
		box-shadow: 5px 5px 0 #b3b3b3;
	}
	```
	</details>
	<details>
	<summary>main.js</summary>

	```js
	import {
		DecoupledEditor,
		GeneralHtmlSupport,
		Heading,
		Style,
	} from 'ckeditor5';
	
	const editorConfig = {
		toolbar: {
			items: [
				'heading',
				'style'
			]
		},
		plugins: [
			GeneralHtmlSupport,
			Heading,
			Style,
		],
		style: {
			definitions: [
				{
					name: 'Article category',
					element: 'h3',
					classes: ['category']
				},
				{
					name: 'Title',
					element: 'h2',
					classes: ['document-title']
				},
				{
					name: 'Subtitle',
					element: 'h3',
					classes: ['document-subtitle']
				},
				{
					name: 'Info box',
					element: 'p',
					classes: ['info-box']
				},
				{
					name: 'Side quote',
					element: 'blockquote',
					classes: ['side-quote']
				},
				{
					name: 'Marker',
					element: 'span',
					classes: ['marker']
				},
				{
					name: 'Spoiler',
					element: 'span',
					classes: ['spoiler']
				},
				{
					name: 'Code (dark)',
					element: 'pre',
					classes: ['fancy-code', 'fancy-code-dark']
				},
				{
					name: 'Code (bright)',
					element: 'pre',
					classes: ['fancy-code', 'fancy-code-bright']
				}
			]
		},
		initialData: '<h2>Congratulations</h2>'
	};
	
	DecoupledEditor.create(document.querySelector('#editor'), editorConfig).then(editor => {
		document.querySelector('#editor-toolbar').appendChild(editor.ui.view.toolbar.element);
	
		return editor;
	});
	```
	</details>
2. Use an HTTP server to run the snippet.
3. Click the Style toolbar component.

### ✔️ Expected result

![image](https://github.com/ckeditor/ckeditor5/assets/2270764/f813a130-2183-4547-93e0-3a380562f9ba)

### ❌ Actual result

![image](https://github.com/ckeditor/ckeditor5/assets/2270764/14f3de57-fcc2-4a39-9f4e-08199662f8dd)

`.ck-content` impacts the toolbar, but also **other editors** that are inside the root one.

### ❓ Possible solution

I can modify the `.ck-content` selector:

```css
.ck-content:not(:is(.ck-sidebar, .ck-toolbar, .ck-body-wrapper) .ck-content) {
```

But it looks weird, and the integrators will not find such examples in our documentation.
