### ISSUE TITLE
CKeditor 5 and MaterializeCSS: no bullet lists in editor

### ISSUE THREAD

**Issue by fkranenburg** [ckeditor/ckeditor5#1672]
🐞 Bug report 

## 💻 CKeditor 5

Using CKEditor 5 and Materialize CSS does not work well. I'm using MaterializeCSS v1.0.
The CSS from the [docs](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/css.html#compatibility-with-materialize)  is applied but it looks like Materializecss is overriding all ul-li tags in the editor.

## 📋 Steps to reproduce

1. go to https://codepen.io/ckeditor/pen/gZebwy
2. add some text
3. use bullet function

## ✅ Expected result
See bullets

## ❎ Actual result
No bullets

**Comment by Mgsy** [comment]
I can confirm that in our MaterializeCSS demo unordered lists miss styles. cc @dkonopka

**Comment by dkonopka** [comment]
By default materialize CSS is overriding default `<ul>` and `<li>` appearance, [see the source code](https://github.com/Dogfalo/materialize/blob/v1-dev/sass/components/_global.scss#L28-L37).

We should add it to our documentation, but ATM current fix can help you.
```css
.ck.ck-content ul,
.ck.ck-content ul li{
  list-style-type: inherit;
}

.ck.ck-content ul {
  /* Default user agent stylesheet, you can change it to your needs. */
  padding-left: 40px;
}
```

I've also updated a [codepen demo](https://codepen.io/ckeditor/pen/gZebwy).
