### ISSUE TITLE
Is having `definitions.xxx.classes` mandatory by intention?

### ISSUE THREAD

**Issue by garvinhicking** [ckeditor/ckeditor5#16737]
## 📝 Ask a question

Having a configuration like this (asking for the context of a default TYPO3 implementation):

```
editor:
  config:
    style:
      definitions:
        # block level styles
        - { name: 'Orange title H2', element: 'h2', classes: ['orange'] }
        - { name: 'Orange title H3', element: 'h3', classes: ['orange'] }
        - { name: 'Quote / Citation', element: 'blockquote', classes: [''] }
        - { name: 'Code block', element: 'code', classes: ['']  }
        # Inline styles
        - { name: 'Yellow marker', element: 'span', classes: ['yellow-marker'] }
```

it seems that `classes` is a required attribute. Also https://ckeditor.com/docs/ckeditor5/latest/api/module_style_styleconfig-StyleDefinition.html does not really mention it as being optional. Leaving such an attribute out leads to the dropdown for styles not getting opened.

If the attribute is required, I wonder how one could implement an empty `<code>` element. Currently, always `<code class="">` is emitted.

Also, when using `classes: []` to indicate an empty array, the element is not choosable at all. Using `classes: false|null|true` only leads to having `<code class="false|null|true">`.

So I wonder, am I missing something here, or would it classify as a bug?
