### ISSUE TITLE
The module duplication check is insufficient

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1692]
There's a case which the current check won't catch.

Background: the current check relies on a single `ckeditor5-utils/src/version` module which registers itself in the global scope and, if there's a duplicated version of this package (happens when adding plugins to an existing build or having completely missmatched versions of dependencies leading to duplicated packages in `node_modules`). Thanks to that, it's able to tell that it's been loaded second time and we're able to warn the developer about this situation.

However, it's not going to catch situations with conflicting versions of dependencies, but in a way which doesn't lead to a duplication of the `ckeditor5-utils` package. E.g.

```
ckeditor5-foo: 1.0.0
   requires:
     ckeditor5-engine: ^12.0.0
        requires:
           ckeditor5-utils: ^11.0.0
     ckeditor5-utils: ^11.0.0

ckeditor5-bar: 1.0.0
  requires:
     ckeditor5-engine: ^13.0.0
        requires:
           ckeditor5-utils: ^11.0.1
```

If your setup requires `ckeditor5-foo` and `ckeditor5-bar` npm/yarn will (**I think**) install:

* `ckeditor5-foo@1.0.0`
* `ckeditor5-bar@1.0.0`
* `ckeditor5-engine@12.0.0`
* `ckeditor5-engine@13.0.0`
* `ckeditor5-utils@11.0.1`

So, there's no duplication of `ckeditor5-utils` because two versions of the engine are happy with its never version.

I'm not 100% sure that npm/yarn will be able to figure out that this is the minimal installation setup, but it's entirely possible that they do or will do that.

Therefore, a separate check, unfortunately, would need to be included in every package that we want to secure. Every plugin and many engine/UI's base modules.

However, the second option is to check this in our webpack plugin. In fact, we planned that the runtime error will be just one of the verification mechanisms. The other was supposed to warn developers even earlier, when running webpack. At that stage, it's completely possible to tell that there are two versions of the engine used.
