### ISSUE TITLE
[Docs] Fake selection container breaks styling

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#1730]
https://ckeditor.com/docs/ckeditor5/latest/framework/guides/tutorials/implementing-an-inline-widget.html#demo

![Apr-26-2019 09-33-52](https://user-images.githubusercontent.com/156149/56791071-7abfe680-6806-11e9-9896-3d3dd45ff7f4.gif)

**Comment by Reinmar** [comment]
We must be really cautious with `:last` and margins.

**Comment by dkonopka** [comment]
So... to sum up, it's a tricky case, right now we are using these styles: 

```css
.ck.ck-content > :first-child {
	margin-top: 0;
}

.ck.ck-content > :last-child {
	margin-bottom: 0;
}
```

With the focused widget, CSS as last-child understands fake selection div with `position: fixed` moved outside the viewport. I've spent some time with this demo, and I've no idea how to perfectly fix it, maybe @oleq will found some solution here, because he was playing with these first/last margins issues AFAIR.

There is a fix for paragraph case only: 
```css
/* #1730. Handle case when widget is placed inside first (and also last) line of the content. */
.ck.ck-content.ck-editor__editable_inline p {
    margin-bottom: var(--ck-spacing-large);
}

.ck.ck-content.ck-editor__editable_inline>:first-child {
    margin-top: var(--ck-spacing-large);
}
```
