### ISSUE TITLE
set style with component in angular 2+ not working

### ISSUE THREAD

**Issue by kapilthakkar2912** [ckeditor/ckeditor5#1770]
## Is this a bug report or feature request? (choose one)

🐞 Bug report  |  🆕 Feature request  |  Other

## 📋 Steps to reproduce

1.
2.

**Comment by kapilthakkar2912** [comment]
:host ::ng-deep .ck-editor__editable {
    min-height: 500px;
}

not working for me with angular 7 and ckEditor 5

**Comment by Mgsy** [comment]
Hello, please try to use:
```css
:host ::ng-deep .ck.ck-editor__editable {
	min-height: 500px;
}
```
