### ISSUE TITLE
Create a binary script for creating a new changelog entry (template)

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#18068]
## Provide a description of the task

We want to expose a binary script (from the `@ckeditor/ckeditor5-dev-changelog` package) that allows the creation of a new changelog entry.

The tool must also accept the modifier, as the generator allows the directory definition with input files.

### Definition of Done

- The binary script does not crash and creates the input directory if it's missing.
- ~When the generated file name has already been taken, add a suffix `-n`. If the file is taken as well, increase `n+1`.~
- When the generated file name has already been taken, delay the script by one second.
- The script creates nested directories based on the current git branch.
	- Example branch: `#epic/ck/18051-changeset`.
	- ~Output file: `.changelog/epic/ck/18051-changeset/YYYY-MM-DD-{1, 2, ..., n}.md`~
	- Output file: `.changelog/20250519153400_epic_ck_18051_changeset.md`
		- _YYYYMMDDHHMMSS_
- The created file contains the following content ([see a comment](https://github.com/ckeditor/ckeditor5/issues/18068#issuecomment-2900334800)):
	```yml
	---
	# Obligatory unless this entry is about a breaking change. If so, it can be safely removed.
	# Accepted values: Feature | Fix | Other
	type:
	
	# Is the entry about a breaking change? If not, you can remove this line.
	# Accepted values: major | minor | true
	breaking-change:
	
	# Non-obligatory. Specify short package names to which this entry applies.
	# It can be safely removed if not needed.
	# Example value: ckeditor5-core
	scope:
	  -
	
	# Non-obligatory. Specify issues that have been closed by this change.
	# Accepted values: #{issue-number} | {repo-owner}/{repo-name}#{issue-number} | URL
	# It can be safely removed if not needed.
	closes:
	  -
	
	# Non-obligatory. Specify issues related to this change.
	# Accepted values: #{issue-number} | {repo-owner}/{repo-name}#{issue-number} | URL
	# It can be safely removed if not needed.
	see:
	  -
	
	# When a community member makes a change, you can specify their GitHub usernames.
	# It can be safely removed if not needed.
	communityCredits:
	  - 
	---
	
	Write a short description of the change in the first line.
	
	You can add additional sentences if they help you understand the context.
	```
- When the file has been created, we should print a path to it, but also leave some instructions on what's next. Example:
	> A new changelog entry has been generated. 
	> 
	> Open the "file:///home/pomek/ckeditor5/.changelog/20250519153400_epic_ck_18051_changeset.md" file and modify it according to your changes.
	> 
	> Be sure to commit it to providing the entry for the upcoming changelog generation once you're done.
- The bin script should be in JS, but the sources should be in TypeScript.
