### ISSUE TITLE
Add formatting to list markers

### ISSUE THREAD

**Issue by mmotyczynska** [ckeditor/ckeditor5#18537]
## 📝 Provide a description of the improvement

**List markers** `before` change (no formatting):

![Image](https://github.com/user-attachments/assets/c62024d6-58c5-4eb1-b133-54739120ca97)

**List markers** `after` change (formatted the same way as the list item content):

![Image](https://github.com/user-attachments/assets/dc1bfcf9-8967-4b36-9b93-ef42d30c4e95)

### List of formats to add to list markers:

- Bold
- Italic
- Font family
- Font size
- Font color

The change should apply to all list types: `numbered`, `bulleted` and `multi-level`.

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
Maybe we could apply styles for markers in this way:
```html
<ol>
  <li 
    class="ck-list-marker-color ck-list-marker-font-size" 
    style="--ck-list-marker-color: blue; --ck-list-marker-font-size: 40px;"
  >foo
    <ol>
      <li>plain</li>
      <li class="ck-list-marker-font-bold">bold</li>
      <li class="ck-list-marker-font-italic">italic</li>
      <li class="ck-list-marker-color" style="--ck-list-marker-color: red;">color</li>
      <li class="ck-list-marker-font-size" style="--ck-list-marker-font-size: 1.7em;">size</li>
      <li class="ck-list-marker-font-family" style="--ck-list-marker-font-family: 'Courier New', Courier, monospace;">family</li>
    </ol>
  </li>
</ol>
```
```css
.ck-list-marker-color::marker {
  color: var(--ck-list-marker-color);
}
.ck-list-marker-font-size::marker {
  font-size: var(--ck-list-marker-font-size);
}
.ck-list-marker-font-family::marker {
  font-family: var(--ck-list-marker-font-family);
}
.ck-list-marker-font-bold::marker {
  font-weight: bold;
}
.ck-list-marker-font-italic::marker {
  font-style: italic;
}
```
This way, we do not need to reset styles on blocks inside a list or even in sublists. I tested it in Chrome, Safari, and Firefox, and it works as expected.
