### ISSUE TITLE
Move classes from table to figure when editing the content

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor5#18637]
## 📝 Provide a description of the improvement

Sometimes, for example in email editing use cases, users have custom stylesheet + classes applied on `<table>` elements. When such content gets loaded into the editor, `<table>` is wrapped in `<figure>` and custom CSS is no longer applied as intended. This causes content to look broken while editing.

Maybe it would be possible to "move" classes from `<table>` to `<figure>` in editing?

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.

**Comment by Witoso** [comment]
Maybe we could extend [this function](https://github.com/ckeditor/ckeditor5/blob/master/packages/ckeditor5-html-support/src/integrations/table.ts#L257-L283) - not only by style attributes, but also included all CSS classes.

**Comment by Witoso** [comment]
After a long discussion, we decided not to do the proposed solution.

1. This is a big breaking change for the current users.
2. Even if we do move classes from `table` to `figure` there's no guarantee that everything will work correctly. Some styles will populate the table below the figure, some won't.

General advice would be to:
* Migrate the content so it's CKEditor 5 compliant. We rely more on the inline styles, as classes have problems as mentioned above.
*  Style the **editing** in a way that it reflects table classes. This way a symmetry may be achieved.
    ```css
    .ck.ck-editor__editable figure:has( > table.classX) {
       /* your styles that are in 'table.classX' selector should be copied here, like: */ 
       width: 30%;
       float: left;
    }

    .ck.ck-editor__editable table.classX) {
       /* overridden table properties to fit the <figure> parent element, like: */ 
       width: 100%;
       float: none;
    }
    ```


In the future we could implement an HTML table feature (not a widget) that could fulfill this scenario better.
