### ISSUE TITLE
How can I preview a video?

### ISSUE THREAD

**Issue by pomek** [ckeditor/ckeditor5#2743]
There is a video from YT. When I press the "play" icon, the video does not play. Nothing happens.

I cannot also open it in a new tab and easily copy the video URL. I must select the video, then click the "Insert media" button then I'm able to copy the URL.

It is not comfortable and (for me) intuitive.

**Comment by castroCrea** [comment]
Hello, this might be due to the fact that you preventDefault here
https://github.com/ckeditor/ckeditor5/blob/b8538dea19326a04ed0ff4d8b0ab346f6be8fc08/packages/ckeditor5-widget/src/widget.js#L177

So if you just preventDefault when a widget is already focus, you have the first click that focus and the seconde one can play.
No ?

**Comment by roopchandsuman** [comment]
we can play video into ckeditor if comment or remove the "ck-media__wrapper" class. I edit and make comment this 

@ckeditor\ckeditor5-media-embed\src\mediaregistry.js line no 225 //attributes.class = 'ck-media__wrapper';

**Comment by tony** [comment]
This will work without requiring a rebuild / editing mediaregistry.js:

```
.ck-editor__editable:not(.ck-read-only) .ck-media__wrapper>:not(.ck-media__placeholder) {
    pointer-events: initial  !important;
}
```

However, it's harder to select / cut / paste the embed.  In order to copy/paste, you have to select the area surrounding the embed.

**Comment by tony** [comment]
Even better, try this:

```css
.ck-editor__editable:not(.ck-read-only) .ck-widget_selected .ck-media__wrapper>:not(.ck-media__placeholder) {                                                                                                                                                                   
  pointer-events: initial  !important;                                                                                                                                                                                                                                         } 
```

This lets you cut/paste the widget after direct selection.

Are there any potential side effects to this one can think of?

Ideally - I think there a real solution would be to have "double clicking" add a class to the wrapper that allows pointer events to pass through, then removing the class when clicking outside it.
