### ISSUE TITLE
The nested editable selection indicator is broken

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5#3208]
When there are colspans/rowspans in cells the border-based selection is messed up:

![selection_041](https://user-images.githubusercontent.com/247363/41599703-43a2480e-73d4-11e8-835a-bfda23e8d6ae.png)

I've found that the `box-shadow: inset` plays well:

![selection_042](https://user-images.githubusercontent.com/247363/41599808-85ea94aa-73d4-11e8-827c-bc59b81b6799.png)

I've used this:
```css
.ck-widget.table {
	& td,
	& th {
		&.ck-editor__nested-editable.ck-editor__nested-editable_focused {
			border-style: none;
			box-shadow: var(--ck-inner-shadow), 0 0, inset 0px 0px 0 1px var(--ck-color-focus-border);
		}
	}
}
```
