### ISSUE TITLE
Bootstrap 3&4 overwrites table default style

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5#3253]
Working on issues related to the bootstrap integration I've found changed `.table` behaviour:

```html
<figure class="table ck-widget ck-widget_selectable">
```

![screenshot 2018-12-07 at 11 25 00](https://user-images.githubusercontent.com/10219857/49642742-2c0adf00-fa14-11e8-9f90-66fef375c3ba.png)

### Bootstrap 4:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_tables.scss#L6

```css
.table {
  width: 100%;
  margin-bottom: $spacer;
  background-color: $table-bg; // Reset for nesting within parents with `background-color`.
}
```

### Bootstrap 3 
https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css

```css
.table {
  width: 100%;
  margin-bottom: 20px;
}
```

cc @oleq
