### ISSUE TITLE
[Chrome] Cursor is not consistent when hovering button's icon

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#3346]
![button-icon-cursor](https://cloud.githubusercontent.com/assets/1099479/18630428/dd98d93c-7e6c-11e6-8b09-1bdf006f7cb5.gif)

To deal with it, either a `<styles>` declaration must be injected into SVG, which is not an option here because not every element using an icon from the sprite should have `cursor: pointer`, or hack it a little bit, like this

``` css
    .ck-button:before {
        content: "";
        display: block;
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        cursor: pointer;
    }
```

The hack works but, TBH, I don't like it.

BTW: We're not alone http://stackoverflow.com/questions/26672936/cursor-pointer-on-svg-element-is-not-working.
