### ISSUE TITLE
[Edge] Confusing (?) clear action in the input fields

### ISSUE THREAD

**Issue by dkonopka** [ckeditor/ckeditor5#3415]
Microsoft Edge by default has enabled "clear button" in the input fields. It is possible to confuse a user, do you agree? We can easily remove it via:
```css
.ck.ck-input-text::-ms-clear {
  display: none;
}
```
![screen shot 2018-07-12 at 13 58 35](https://user-images.githubusercontent.com/10219857/42681399-d91d4526-8687-11e8-9340-9220c9eea552.png)
