### ISSUE TITLE
StickyPanel behaves weird inside overflowed element

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5#5465]
StickyPanel should listen to scroll event of all of its ancestors not only on the `window` object.
The same as `BalloonPanelView` does: https://github.com/ckeditor/ckeditor5-ui/blob/beb9f96615da05f22166fb8ddfa7838333b1b61f/src/panel/balloon/balloonpanelview.js#L326-L340 (we can consider moving this listener from BPV to some util).

Besides panel should take only the visible part of the limiter rect into consideration.

Now when classic editor is inside overflowed container then sticky top bar behaves weird.

![jun-04-2018 15-53-58](https://user-images.githubusercontent.com/1057056/40921432-b6775ca0-680f-11e8-89ab-53cd7066dc0e.gif)

**Comment by petrvorobev** [comment]
confirmed

**Comment by akhilxavierm** [comment]
This CSS would fix the issue
`.ck .ck-sticky-panel .ck-sticky-panel__content_sticky{
  position: static !important;
}`

**Comment by flyher** [comment]
> 
> 
> This CSS would fix the issue
> `.ck .ck-sticky-panel .ck-sticky-panel__content_sticky{ position: static !important; }`


Thanks @akhilxavierm , this works well.
Maybe we can add the following css to solved the issue temporary.

```css
// default global
.ck .ck-sticky-panel .ck-sticky-panel__content_sticky {
    position: static !important;
}

// blur
.ck-editor__top {
      height: 1px;
      overflow: hidden;
}

// focus
.ck-editor__top {
      display: block;
      height: 38.67px;
      .ck-sticky-panel__placeholder {
        display: none !important;
      }
}
```
