### ISSUE TITLE
Dropdown panel should not not be cut off when the editor is inside in an overflow: hidden host

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5514]
ATM the dropdown recognizes the boundaries of the viewport and positions accordingly:

![image](https://user-images.githubusercontent.com/1099479/60428953-4b5c9a00-9bfa-11e9-9b10-825f78bbb5aa.png)

![image](https://user-images.githubusercontent.com/1099479/60428960-51527b00-9bfa-11e9-9716-e0b5637b227e.png)

But it does not recognize the `overflow: hidden` ancestors and gets cut off, which is definitely annoying. It makes it impossible to use dropdown in the toolbar in modal windows if the dropdown is to be somewhere later in the toolbar (closer to the right edge).

![image](https://user-images.githubusercontent.com/1099479/60428843-17817480-9bfa-11e9-84ac-88ee30130e0a.png)

**Comment by datasoysa** [comment]
Issue seems a bit old and closed, but I still have the problem. Should we reopen this one or generate a new ticket I don't know but only thing i can tell that the approach by trying to understand the overflow:hidden ancestors won't work. As my condition it didn't work, It have a grid, grid-item with overflow-hidden and a flex-box stretches the content. Solution should be applied on a bit more generic way. And I'm sure that it will be more easier than understanding the ancestors. Create an overlay element on top of everything. for example a div element with position static at the end of body and locate your dropdowns inside that according to the reference elements .getBoundingClientRect().top and left and of course width. Than you'll never fall in to dropdown crops.

**Comment by kvas-damian** [comment]
the same problem appears when CKEditor is rendered inside vertically scrollable container. For vertically scrollable container browsers, browser cut/hide content that overlaps horizontally (similar to `overflow-x: hidden` but you cannot override it).
Example: https://codepen.io/kvas-damian/pen/xxjEYXb

**Comment by ikhidebright** [comment]
This is still an issue, its sad

**Comment by nechutny** [comment]
This can be easily fixed with CSS anchors

```css
.ck.ck-dropdown {
		anchor-name: --ck-dropdown;

		.ck.ck-dropdown__panel {
			position: fixed;
			position-anchor: --ck-dropdown;
			top: anchor(bottom);
			left: anchor(left);
			z-index: 99999;
			transform: none;
			min-width: auto;
		}
	}
```

but currently it supports only Chrome based browsers. But still better then nothing.
