### ISSUE TITLE
Toolbar button focus indication has too low contrast

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5#5580]
## 📝 Provide detailed reproduction steps (if any)

1. Open an [example editor with toolbar](https://ckeditor.com/docs/ckeditor5/12.4.0/features/basic-styles.html).
2. Press `alt + f10` to focus the toolbar.
3. Examine focus outline color.

![Eduitor UI with a button focused and a low contrast outline on a button](https://user-images.githubusercontent.com/5353898/66741280-6d122200-ee75-11e9-81ef-ccdb969dd91f.png)

### ✔️ Expected result

The contrast ratio of the outline to background should meet at least WCAG level AA standard.

### ❌ Actual result

Contrast is too low and doesn't match WCAG level AA. It's 1.36:1 (`#C5DAF8` to `#FAFAFA`).

## 📃 Other details

* CKEditor version: 12.4.0

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mlewand** [comment]
For anyone facing this issue there's a simple workaround that require you to add CSS like the following:

```css
.ck-editor .ck.ck-button:active, .ck-editor .ck.ck-button:focus, .ck-editor a.ck.ck-button:active, .ck-editor a.ck.ck-button:focus {
	box-shadow: 0 0 0px 3px #1250A5;
}
```

You can see it here https://codepen.io/mlewand/pen/yLLOyME
