### ISSUE TITLE
Page break content styles get incorrectly exported

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5605]
What we get right now in content styles is this:

```css
/* ckeditor5-page-break/theme/pagebreak.css */
.ck-content .page-break {
	position: relative;
	clear: both;
	padding: 5px 0;
	display: flex;
	align-items: center;
	justify-content: center
}
/* ckeditor5-page-break/theme/pagebreak.css */
.ck-content .page-break::after {
	content: '';
	position: absolute;
	border-bottom: 2px dashed hsl(0, 0%, 77%);
	width: 100%;
}
/* ckeditor5-page-break/theme/pagebreak.css */
.ck-content .page-break__label {
	position: relative;
	z-index: 1;
	padding: .3em .6em;
	display: block;
	text-transform: uppercase;
	border: 1px solid hsl(0, 0%, 77%);
	border-radius: 2px;
	font-family: Helvetica, Arial, Tahoma, Verdana, Sans-Serif;
	font-size: 0.75em;
	font-weight: bold;
	color: hsl(0, 0%, 20%);
	background: #fff;
	box-shadow: 2px 2px 1px hsla(0, 0%, 0%, 0.15);
	-webkit-user-select: none;
	-moz-user-select: none;
	-ms-user-select: none;
	user-select: none;
}
/* ckeditor5-page-break/theme/pagebreak.css */
.ck-content .page-break {
	padding: 0
}
/* ckeditor5-page-break/theme/pagebreak.css */
.ck-content .page-break::after {
	display: none;
}
```

Those rules override each other. And I don't know if this is a problem in the export tool or the CSS for this feature is written this way. It'd also be good to check if those styles actually work the way we wanted them to work (and I don't remember now what we decided – how page breaks should appear when using data + content styles).
