### ISSUE TITLE
Consider a better look for a page-break

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5630]
### ATM

<img width="876" alt="Screenshot 2019-10-18 at 12 01 48" src="https://user-images.githubusercontent.com/1099479/67085421-1707ec00-f19f-11e9-892b-198cfd727538.png">

### What it could look like

<img width="874" alt="Screenshot 2019-10-18 at 11 47 48" src="https://user-images.githubusercontent.com/1099479/67085372-f9d31d80-f19e-11e9-89cc-e4538c23fc3f.png">
<img width="953" alt="Screenshot 2019-10-18 at 11 59 01" src="https://user-images.githubusercontent.com/1099479/67085373-f9d31d80-f19e-11e9-9937-23c16a964f37.png">
<img width="886" alt="Screenshot 2019-10-18 at 11 59 27" src="https://user-images.githubusercontent.com/1099479/67085376-f9d31d80-f19e-11e9-8c6e-aa4dc7724403.png">
<img width="832" alt="Screenshot 2019-10-18 at 12 00 23" src="https://user-images.githubusercontent.com/1099479/67085377-fa6bb400-f19e-11e9-94a7-3b021ce61c23.png">

CSS used for the new look

```css
.ck-content .page-break {
    position: relative;
    clear: both;
    padding: 5px 0;
    display: flex;
    align-items: center;
    justify-content: center;
    background-image: linear-gradient(90deg, #e4e4e4, #e4e4e4 75%, transparent 75%, transparent 100%);
    background-size: 6px 1px;
    background-repeat: repeat-x;
    background-position: center;
}

.ck-content .page-break:before {
    content: "";
    top: 0;
    position: absolute;
    border-left: 1px solid;
    border-right: 1px solid;
    border-bottom: 1px solid;
    border-image: linear-gradient( to top, #c4c4c4, transparent ) 1;
    width: 100%;
    height: 9px;
    box-shadow: 0 3px 2px rgba(0,0,0,0.05);
}

.ck-content .page-break::after {
    border-left: 1px solid;
    border-right: 1px solid;
    border-top: 1px solid;
    border-image: linear-gradient( to top, transparent, #c4c4c4 ) 1;
    bottom: 0;
    content: "";
    position: absolute;
    width: 100%;
    height: 9px;
    box-shadow: 0 -3px 2px rgba(0,0,0,0.05);
}

.ck-content .page-break__label {
    position: relative;
    text-align: center;
    z-index: 10;
    text-transform: uppercase;
    border-radius: 2px;
    font-family: Helvetica,Arial,Tahoma,Verdana,Sans-Serif;
    font-size: 0.65em;
    font-weight: 700;
    color: #333;
    background: #fff;
    margin: 1em;
    padding: 0.1em 1em;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

cc @dkonopka @Reinmar 

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.
