### ISSUE TITLE
Highlight buttons should work with the inverted ("dark") themes

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#5681]
## 📝 Provide a description of the new feature

ATM it looks like this

<img width="832" alt="Screenshot 2019-10-29 at 10 57 52" src="https://user-images.githubusercontent.com/1099479/67757152-8e5d3b80-fa3b-11e9-89a6-aa3603b1b0f8.png">

While developers would rather have something like this instead:

<img width="832" alt="Screenshot 2019-10-29 at 10 57 38" src="https://user-images.githubusercontent.com/1099479/67757171-97e6a380-fa3b-11e9-9fe9-d270205e9450.png">

but the latter is impossible (very hard) to do because only the inner part of the SVG gets the `fill` from JS

![image](https://user-images.githubusercontent.com/1099479/67757244-b482db80-fa3b-11e9-9860-88491e748eba.png)

and there's no way to tell from the outside (CSS) which marker a particular icon represents. What we need is probably a CSS class set on the button (or the icon) that will allow developers to customize highlight buttons, for instance:

```css
/* Make the icon colorful where it would normally be white. */
.ck .ck.ck-highlight_marker_yellow path {
    fill: var(--ck-highlight-marker-yellow);
}

/* Make the "inside" transparent */
.ck .ck.ck-highlight_marker_yellow path.ck-icon__fill {
    fill: transparent !important;
}
```

A follow–up of https://github.com/ckeditor/ckeditor5-theme-lark/pull/247.

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.
