### ISSUE TITLE
change the default h1 css style

### ISSUE THREAD

**Issue by shakthifuture** [ckeditor/ckeditor5#6210]
In below code, how to change the default h1 CSS style? or how can I replace our own custom CSS style class?

heading: {
            options: [
                { model: 'paragraph', title: 'Paragraph', class: 'ck-heading_paragraph' },
                { model: 'heading1', **view: 'h1'**, title: 'Heading 1', class: 'ck-heading_heading1' },
                { model: 'heading2', view: 'h2', title: 'Heading 2', class: 'ck-heading_heading2' }
            ]
        }
source: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/configuration.html

**Comment by FilipTokarski** [comment]
Hi, to modify css styles of header elements in the editor content, you can just add css rules for every header element, for example:
```css
<style>
.ck > h1 {
    font-size: 20px;
}
.ck > h2 {
    font-size: 15px;
}
.ck > h3 {
    font-size: 5px;
}
</style>
```
Hope that helps!
