### ISSUE TITLE
Mark UI buttons in the guides to improve discoverability

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6267]
## 📝 Provide a description of the improvement

Personally, sometimes I feel it's pretty hard to figure out which button among dozens is "the one" a particular guide is about. This could be even a bigger problem for people unfamiliar with the editor. My idea is we could add some classes via JS in the samples (and some styles) and help readers find the right place to start.

### The halo approach

<img width="915" alt="Screenshot 2020-02-14 at 11 54 59" src="https://user-images.githubusercontent.com/1099479/74525316-1438c000-4f21-11ea-8761-e370cd3487fc.png">

```css
.ck.ck-dropdown.foo > .ck-button::after {
    content: "";
    background: #ff000014;
    border-radius: 100px;
    width: 60px;
    height: 60px;
    display: block;
    position: absolute;
    top: 50%;
    border: 3px solid #ff00008a;
    left: 50%;
    transform: translate(-50%,-50%);
    z-index: -1;
    pointer-events: none;
}

.ck.ck-dropdown.foo button.ck.ck-button {
    z-index: 0;
    position: relative;
}
```

### The tooltip approach

<img width="909" alt="Screenshot 2020-02-14 at 11 54 25" src="https://user-images.githubusercontent.com/1099479/74525307-0f740c00-4f21-11ea-9c50-2ec2017fd860.png">

```css
.ck.ck-dropdown.foo > .ck-button::after {
    content: "Check this out!";
    background: #ff5b61;
    padding: 3px 5px;
    border-radius: 3px;
    font-size: 10px;
    color: #fff;
    display: block;
    position: absolute;
    top: 0;
    left: 50%;
    transform: translate(-50%,calc(-100% - 8px));
    z-index: -1;
    pointer-events: none;
}

.ck.ck-dropdown.foo > .ck-button::before {
    content: "";
    display: block;
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 5px 5px 0 5px;
    border-color: #ff5b61 transparent transparent transparent;
    position: absolute;
    top: 0;
    left: 50%;
    transform: translate(-50%, -8px);
}
```

@Reinmar @AnnaTomanek 

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.
