### ISSUE TITLE
The live preview of the table cell background should work with multiple-cell selection

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5#6446]
## 📝 Provide detailed reproduction steps (if any)

When the selection is in a cell, it works just fine. But when we display selected cell styles for multi-selection, they override the background.

This is almost impossible to fix unless we drop selected table cells' backgrounds completely in favor of borders.

![2020-03-16 13 34 41](https://user-images.githubusercontent.com/1099479/76759087-48570900-678b-11ea-951c-a6e67a73698f.gif)

## 📃 Other details

Somehow but not directly related https://github.com/ckeditor/ckeditor5/issues/6425.

cc @panr 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by panr** [comment]
Yeah, I know. Just wanted to issue it too 🙈 

> This is almost impossible to fix

Not really, when we move selection color to `:after` element then we can create a sami-transparent overlay over the cells. This may cause some other issues (related to `position: relative` on `td.ck-editor__editable_selected`), but... We can try it ;-)

**Comment by Reinmar** [comment]
@panr Could you make a quick POC?

**Comment by oleq** [comment]
I checked and

```css
td.ck-editor__editable.ck-editor__nested-editable {
    position: relative;
}
```

```css
td.ck-editor__editable.ck-editor__nested-editable::after {
    content: "";
    background: red;
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    pointer-events: none;
    opacity: .2;
}
```

gives promising results

![image](https://user-images.githubusercontent.com/1099479/77433862-4242d700-6de0-11ea-9eb2-b41b0a920fed.png)
