### ISSUE TITLE
Table header content styles do not contain text-alignment (which is controlled by the dir=ltr/rtl attribute)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6638]
## 📝 Provide detailed reproduction steps (if any)

Currently, the text alignment of a table header cells (`<th>` elements) are controlled by:

https://github.com/ckeditor/ckeditor5-theme-lark/blob/5f9c8f2b4637a351c755c8e77556bf2e74c66024/theme/ckeditor5-ui/components/editorui/editorui.css#L30-L36

This is a bit accidental but when adding support for RTL/LTR content we agreed with @oleq that it's acceptable.

The problem is that these styles do not use `.ck-content` so they are missing in https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html.

I'd propose adding this:

```css
.ck-content[dir="ltr"] .table th {
	text-align: left;
}

.ck-content[dir="rtl"] .table th {
	text-align: right;
}
```

to `table.css` and explain in the aforementioned guide that if you want to have the same styles when the content is displayed on your page, you also need to set the `dir` attribute correctly.

cc @oleq 

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.
