### ISSUE TITLE
How to make table border=none setting work?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#6841]
## 📝 Provide a description of the improvement

If you set table borders to none this is what you'll likely see:

![](https://user-images.githubusercontent.com/156149/82222202-3f1c2100-9921-11ea-936d-b2edd3fd16c4.png)

The table still has a border. Why does it happen? It's because the table is styled by [default content styles](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/content-styles.html#the-full-list-of-content-styles) to this:

![](https://user-images.githubusercontent.com/156149/82222368-75f23700-9921-11ea-9fc0-7438f02aafc6.png)

These styles are applied by default **via a stylesheet** to every table in the editor. Since the "none" style set in the "Table properties" balloon does **not** apply any inline style to the `<table>` element, the styles coming from the stylesheet are applied.

Therefore, in order to make a table not have any border by default one needs to add such a CSS to their website's styles (note: `td`s need to be styled too):

```css
body .ck-content .table table, body .ck-content .table td {
	border: none;
}
```

With this style, you'll get:

![](https://user-images.githubusercontent.com/156149/82222762-09c40300-9922-11ea-8fe0-ed1575a10a58.png)

However, this isn't perfect – the table is now rendered in a very unclear way. Therefore, it's better to load different stylesheet in a page where the editor is rendered and in a page where the editor contents is rendered:

```css
/* page-with-editor.css */
body .ck-content .table table, body .ck-content .table td {
	border: dotted 1px #eee;
}
```

```css
/* page-with-editor-content.css */
body .ck-content .table table, body .ck-content .table td {
	border: none;
}
```

This will make the table visible when rendered in the editor even if it has no border set via the "Table properties" and "Table cell properties" balloons:

![](https://user-images.githubusercontent.com/156149/82223208-a8506400-9922-11ea-9208-49d5ef776d15.png)

While ensuring that everything still works when the table is being styled via the balloons:

![](https://user-images.githubusercontent.com/156149/82223269-bd2cf780-9922-11ea-9684-2284833d5931.png)

And that the border is not rendered at all if it was not set via the balloon when the content outputted from the editor is rendered on a target page (that uses `page-with-editor-content.css`).

## Should we do something with this?

It may be confusing for some developers why setting borders to none via the UI does not make the borders disappear completely. It'd be good to at least point in the documentation to this ticket.

However, perhaps we should do more?

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.
