### ISSUE TITLE
[Docs] Heading placeholder displays incorrectly

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor5#9091]
## 📝 Provide detailed reproduction steps (if any)

1.  Go to http://localhost:8080/ckeditor5/25.0.0/features/editor-placeholder.html.
2.  Change the first block to a heading.

### ✔️ Expected result

The placeholder doesn't change position.

### ❌ Actual result

The placeholder moves to the left edge of the editor.

## 📃 Other details

![](https://user-images.githubusercontent.com/20988892/108998762-a8e00d00-76a1-11eb-84cc-6e688bc73f7d.gif)

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by niegowski** [comment]
This is because of this CSS rule: 

```css
.live-snippet .ck.ck-content h2, .live-snippet .ck.ck-content h3, .live-snippet .ck.ck-content h4 {
    position: static;
}
```

it's overriding this:

```css
.ck.ck-placeholder, .ck .ck-placeholder {
    position: relative;
}
```
