### ISSUE TITLE
Block Toolbar Panel: Position above?

### ISSUE THREAD

**Issue by tony** [ckeditor/ckeditor5#9205]
## 📝 Provide a description of the improvement

Right now, moving panel via transform affects both block editor and balloon editor:

> To adjust the position of the block toolbar button to match the styles of your website, use the CSS transform property:
>
> ```css
> .ck.ck-block-toolbar-button {
>   transform: translateX( -10px );
> }
> ```

Docs:
- https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_toolbar_block_blocktoolbar-BlockToolbar.html
- https://ckeditor.com/docs/ckeditor5/latest/features/toolbar/blocktoolbar.html#configuration

Consider the following:

```css
.ck.ck-block-toolbar-button {
    transform: translateY( -96px );
}
```

Both the block toolbar and balloon toolbar will be styled. 

![image](https://user-images.githubusercontent.com/26336/110673200-1a39b880-8196-11eb-8a3c-7353cf820018.png)

## 📃 Other details

1. Small fix: The class names in both the balloon and block editor are the same (except for `arrow_s` / `arrow_n`). If we added a differentiated class name to each component, we could style them separately

   ![image](https://user-images.githubusercontent.com/26336/110674115-2ffbad80-8197-11eb-965c-2d4c85c0cefb.png)

2. Positioning which direction the pointy arrow is at 

    ![image](https://user-images.githubusercontent.com/26336/110673504-7997c880-8196-11eb-84de-7414719d7899.png)

    I assume CSS could do this
3. Bigger idea: Allow configuration placement of both panels top/bottom/below via options

* Browser: …
* OS: …
* CKEditor version: v26
* Installed CKEditor plugins: Balloon block editor build

## Workaround (SCSS Hack)

This doesn't specify the toolbar type (block/balloon/etc) it just makes it so bottom toolbars appear on top and have the arrow flipped.

```scss
  &.ck-balloon-panel.ck-toolbar-container.ck-balloon-panel_arrow_n {
    transform: translateY( -96px );

    &:before {
      content: unset;
    }
    &:after {
      left: 50%;
      margin-left: calc(var(--ck-balloon-arrow-half-width)*-1);
      top: unset;
      transform: rotate(180deg) scaleX(-1);
      bottom: calc(var(--ck-balloon-arrow-height)*-1);
    }
  }
```

![image](https://user-images.githubusercontent.com/26336/110681707-ba480f80-819f-11eb-9141-c1c0f5b1e0bd.png)

---

If you'd like to see this improvement implemented, add a 👍 reaction to this post.
