### ISSUE TITLE
When turning a fullwidth image into a right-centered one, it remains very big

### ISSUE THREAD

**Issue by neongreen** [ckeditor/ckeditor5#9309]
## 📝 Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/ckeditor-5/demo/
2. Paste any image at the beginning of the first paragraph
3. Make it right-centered

### ✔️ Expected result

The image is 50% wide.

### ❌ Actual result

The image is almost full-width.

https://user-images.githubusercontent.com/1523306/111848734-19c6bd80-890c-11eb-876b-4763aa1b7d68.mov

## 📃 Other details

* Browser: Chrome
* OS: macOS

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by neongreen** [comment]
I think this only started to happen in one of the recent versions.

**Comment by FilipTokarski** [comment]
Hi, the demo you linked has [presentational styles default configuration](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#presentational-styles) which uses this style:
```css
/* ckeditor5-image/theme/imagestyle.css */
.ck-content .image-style-align-right {
    float: right;
    margin-left: var(--ck-image-style-spacing);
}
```
And as the documentation states:

> Presentational image styles should be combined with the optional image resize feature as these features were designed to be used together. The image width is then controlled by the image resize feature.
> 
> If you do not enable the image resize feature in your setup using the default presentational styles, your images will always take up 100% of the editor width so the alignment may not be visible.
  
Hence the image can be resized by using the resize handle, but does not resize itself by default when aligning.  
On the other hand, thare are also [semantical styles](https://ckeditor.com/docs/ckeditor5/latest/features/image.html#semantical-styles), controlled by:
```css
/* ckeditor5-image/theme/imagestyle.css */
.ck-content .image-style-side {
    float: right;
    margin-left: var(--ck-image-style-spacing);
    max-width: 50%;
}
```
I guess that's the behavior you expected. 

> I think this only started to happen in one of the recent versions.

This split between different image style types was introduced in version `21.0.0`

**Comment by neongreen** [comment]
> but does not resize itself by default when aligning.

It does. After aligning, the image becomes slightly smaller (95% or 90% if I had to guess).

I want the image to be resized to 50% after setting left- or right- alignment, and I want the resizing handle to still work. Is it possible?

**Comment by FilipTokarski** [comment]
I achieved this effect using [presentational styles](https://ckeditor.com/docs/ckeditor5/21.0.0/features/image.html#presentational-styles) configuration and adding these css rules:
```css
.image-style-align-left{
        max-width: 50%;
}
.image-style-align-right{
        max-width: 50%;
}
```
I also had to set the editor width to make it work properly. Now, after uploading the image, it behaves like this:  

https://user-images.githubusercontent.com/34380544/112126449-c206ab80-8bc4-11eb-8cfc-85c797d093d2.mp4

Please let me know if this helps with your use case.
