### ISSUE TITLE
How to set a custom style blockquote

### ISSUE THREAD

**Issue by liwuming** [ckeditor/ckeditor5#9452]
How to set a custom style blockquote, for example, when adding a blockquote, you can select success, error, warning and other custom styles in the upper right corner just like code
```html
<blockquote class="success">hello world</blockquote>
<blockquote class="error">hello world</blockquote>
<blockquote class="warning">hello world</blockquote>
```
I am a Chinese and my English is poor

**Comment by Mgsy** [comment]
Hi, by default CKEditor 5 has one type of blockquote with no classes. It could be styled with CSS, the default styles look like below:

```css
.ck-content blockquote {
    overflow: hidden;
    padding-right: 1.5em;
    padding-left: 1.5em;
    margin-left: 0;
    margin-right: 0;
    font-style: italic;
    border-left: solid 5px hsl(0, 0%, 80%);
}
```

If you'd like to introduce classes to blockquote element and inserting different types, you should create a custom plugin.
