### ISSUE TITLE
Add Scroll in dropdown list of a toolbar option ?

### ISSUE THREAD

**Issue by gauravjain028** [ckeditor/ckeditor5#952]
##  🆕 Feature request 
Is it possible to show scroll bar in the dropdown in toolbar? 
For example, I am using Font plugin, which has font family and size. If I have many options then it shows long dropdown. I guess it is not only related with font plugin, it is related with Dropdown view.

![screenshot from 2018-04-09 12-01-12](https://user-images.githubusercontent.com/2246860/38490516-ecbb9586-3c06-11e8-8d10-bc6b75404809.png)

Is there any workaround for it?

**Comment by Reinmar** [comment]
cc @oleq @dkonopka 

Can we have some reasonable max-height?

And what would be a workaround until we change this on our side?

**Comment by oleq** [comment]
```css
.ck.ck-dropdown__panel {
	max-height: 160px; /* or anything else, more likely ~300px or so */
	overflow-y: auto;
}
```

This should become a part of our codebase. 

![image](https://user-images.githubusercontent.com/1099479/38503000-378fdc52-3c11-11e8-8f0f-e4d84da913d1.png)

**Comment by Reinmar** [comment]
Why so small height? There's plenty of space in the viewport (usually). I think that the point of limiting the height was that if the number of options is too big the height of the panel exceeds the height of the viewport. 

Btw, remember that panel with scroll work terribly so we wanted to avoid them. The issue is that you can't capture scroll event in them (easily) so the entire page starts to scroll.

**Comment by dkonopka** [comment]
Like @Reinmar I would go with something really long (at least 400px), even Google is trying to avoid "double scroll" issue with soooo long dropdowns. 

I was thinking about using [Viewport units](https://caniuse.com/#feat=viewport-units), I mean - `vh` property, but firstly we need research in case of some unexpected bugs.

```css
.ck.ck-dropdown__panel {
	max-height: 90vh;
	overflow-y: auto;
}
```

<img width="347" alt="screen shot 2018-04-10 at 08 46 37" src="https://user-images.githubusercontent.com/10219857/38540312-d90e9f7a-3c9b-11e8-9ae5-8e8ef00b428b.png">

**Comment by long-lazuli** [comment]
That is something that could be handled by a CSS custom-property for me.
```css
.ck.ck-dropdown__panel {
	max-height: var(--ck-editor-dropdown-max-height, 60vh);
	overflow-y: auto;
}
```
and in the dropdown plugin, or in theme plugin, I don't know :
```js
...
  init(){
    const editorHeight = editor.element.nextElementSibling.clientHeight
    editor.element.style.setProperty('--ck-editor-dropdown-max-height', `${editorHeight}px`)
    ...
  }
...
```
