### ISSUE TITLE
Image guide: GMaps pins are too high?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#9955]
## 📝 Provide a description of requested docs changes

I've been checking https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-overview.html

![](https://user-images.githubusercontent.com/156149/123420755-3eda6480-d5bc-11eb-8afd-f1805e0a430b.png)

IDK if that's rendered now as it was supposed to be, but to me it looks like a glitch that these pins in the text are above it. They also split the paragraphs in an odd manner.

**Comment by Reinmar** [comment]
Actually, I think that we mistakenly added margins because it looks bad here too:

![](https://user-images.githubusercontent.com/156149/123420985-8fea5880-d5bc-11eb-875f-a76629341cfa.png)

This is an inline image and I wanted to report another ticket to remove these margins because it's inline but it looks as if it was above the "vious articles" line.

**Comment by godai78** [comment]
Can you provide technical context, like browser etc. In my Chrome this looks like this:

![](https://user-images.githubusercontent.com/68123541/123421369-08e9b000-d5bd-11eb-8a5e-85fe938edc5d.png)

**Comment by niegowski** [comment]
I have the same effect in chrome. Isn't is related to recent changes in umberto with the ability to embed editor icons?

**Comment by Reinmar** [comment]
I use Chrome with enabled Grammarly. I tested it here: [https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-overview.html](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/images/images-overview.html)

The same is true on Firefox, so it's not related to the browser or Grammarly.

**Comment by pomek** [comment]
It looks that I wrote invalid CSS selector. Previously it was:

```css
.formatted p img {
    display: block;
    margin: 1.5em auto;
    box-sizing: content-box;
}
```

And the content looks good.

![image](https://user-images.githubusercontent.com/2270764/123432691-ec547480-d5ca-11eb-9b18-d052fc43b6e6.png)

Currently:

```css
.formatted p img:not(.editor-icon__image) {
    display: block;
    margin: 1.5em auto;
    box-sizing: content-box;
}
```

Looks just bad:

![image](https://user-images.githubusercontent.com/2270764/123432766-fd04ea80-d5ca-11eb-8a51-e999afd35e01.png)
